<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Package.props" />

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <Description>A fast crypto library for .NET.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CryptoBase.Benchmark" />
    <InternalsVisibleTo Include="CryptoBase.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoBase.Abstractions\CryptoBase.Abstractions.csproj" />
  </ItemGroup>

</Project>
