global using CryptoBase.Abstractions.Digests;
global using CryptoBase.Abstractions.SymmetricCryptos;
global using CryptoBase.Digests.CRC32;
global using CryptoBase.Digests.CRC32C;
global using CryptoBase.Digests.MD5;
global using CryptoBase.Digests.SHA1;
global using CryptoBase.Digests.SHA256;
global using CryptoBase.Digests.SHA384;
global using CryptoBase.Digests.SHA512;
global using CryptoBase.Digests.SM3;
global using System.Buffers;
global using System.Buffers.Binary;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Intrinsics;
global using System.Runtime.Intrinsics.Arm;
global using System.Runtime.Intrinsics.X86;
global using System.Security.Cryptography;
global using AesArm = System.Runtime.Intrinsics.Arm.Aes;
global using AesX86 = System.Runtime.Intrinsics.X86.Aes;
