<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="BenchmarkDotNet.TestAdapter" Version="0.15.8" />
    <PackageVersion Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />
    <PackageVersion Include="System.IO.Hashing" Version="10.0.12" />
    <PackageVersion Include="System.Numerics.Tensors" Version="10.0.12" />
    <PackageVersion Include="TUnit" Version="1.66.27" />
  </ItemGroup>
</Project>