<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Package.props" />

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>Abstractions for CryptoBase.</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CryptoBase" />
    <InternalsVisibleTo Include="CryptoBase.Benchmark" />
    <InternalsVisibleTo Include="CryptoBase.Tests" />
  </ItemGroup>

</Project>
