[package]
name = "cryptobase"
version = "1.0.0"
edition = "2021"

[dependencies]
libc = "0.2.126"
digest = { version = "0.10.3", optional = true }
md-5 = { version = "0.10.1", optional = true }
sm3 = { version = "0.4.1", optional = true }

[target.'cfg(all(unix, any(target_arch = "x86", target_arch = "x86_64")))'.dependencies]
md-5 = { version = "0.10.1", features = ["asm"], optional = true }

[profile.release]
lto = true
strip = true

[lib]
name = "cryptobase_native"
crate-type = ["cdylib"]

[features]
default = ["hash"]
hash = ["digest", "md5", "sm3"]
md5 = ["md-5"]
sm3 = ["dep:sm3"]
