<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CryptoBase\CryptoBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyMetadata Include="WycheproofTestVectors" Value="$(MSBuildThisFileDirectory)../wycheproof/testvectors_v1" />
  </ItemGroup>

</Project>
