<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="System.IO.Hashing" />
    <PackageReference Include="System.Numerics.Tensors" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CryptoBase\CryptoBase.csproj" />
  </ItemGroup>

</Project>
